version: '3.8'

services:
  portfolio-frontend:
    build: .
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    command: npm run dev
    restart: unless-stopped